# Configuration du serveur
server.port=8090

# Configuration du logging
logging.level.root=INFO
logging.level.com.rbens=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Configuration des messages
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# Configuration du cache
spring.cache.type=caffeine

# Configuration de Jackson
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss